services:
  redis:
    image: redis:alpine
    container_name: sipel-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: sipel-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Necessário para Linux/Docker em alguns ambientes, boa prática

  grafana:
    image: grafana/grafana:latest
    container_name: sipel-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha inicial
    depends_on:
      - prometheus
