global:
  scrape_interval: 10s # Aumentado levemente para economizar recursos em produção

scrape_configs:
  - job_name: 'sipel-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend.railway.internal:8080'] # Padrão de rede interna do Railway